# Generated by Django 4.1.4 on 2023-03-23 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_monitoring', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storebusinesshour',
            name='store',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restaurant_monitoring.store'),
        ),
        migrations.AlterField(
            model_name='storebusinesshour',
            name='timestamp_utc',
            field=models.DateTimeField(default=None),
        ),
    ]
