# Generated by Django 4.1.4 on 2023-03-22 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_monitoring', '0002_files'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
    ]
