# Generated by Django 4.1.4 on 2023-03-22 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_monitoring', '0003_delete_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_id',
            field=models.TextField(default=uuid.UUID('64c67b94-9548-4e02-8877-ad1de1ac2f31')),
        ),
        migrations.AlterField(
            model_name='store',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
