# Generated by Django 4.1.4 on 2023-03-22 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_monitoring', '0004_store_store_id_alter_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='id',
        ),
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.TextField(default=uuid.UUID('adf84c60-de1e-4de7-aad9-71f68bfd5a8c'), primary_key=True, serialize=False),
        ),
    ]
