# Generated by Django 4.1.4 on 2023-03-22 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant_monitoring', '0005_remove_store_id_alter_store_store_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='store_id',
            field=models.TextField(default=uuid.UUID('c9d603d6-0b68-413d-adca-646798727431'), primary_key=True, serialize=False),
        ),
    ]
